/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_foo_test_handlers_FooHandler */

#ifndef _Included_com_lgc_test_handlers_FooHandler
#define _Included_com_lgc_test_handlers_FooHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_foo_test_handlers_FooHandler
 * Method:    embedQtWidget
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_foo_test_handlers_FooHandler_embedQtWidget
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
